chore(deps): update dependency prettier to v3.6.1 (#1887)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [prettier](https://prettier.io)
([source](https://redirect.github.com/prettier/prettier)) | [`3.6.0` ->
`3.6.1`](https://renovatebot.com/diffs/npm/prettier/3.6.0/3.6.1) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.6.0/3.6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.6.0/3.6.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.6.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#361)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)


[diff](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)

##### TypeScript: Allow const without initializer
([#&#8203;17650](https://redirect.github.com/prettier/prettier/pull/17650),
[#&#8203;17654](https://redirect.github.com/prettier/prettier/pull/17654)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
export const version: string;

// Prettier 3.6.0 (--parser=babel-ts)
SyntaxError: Unexpected token (1:21)
> 1 | export const version: string;
    |                     ^

// Prettier 3.6.0 (--parser=oxc-ts)
SyntaxError: Missing initializer in const declaration (1:14)
> 1 | export const version: string;
    |              ^^^^^^^^^^^^^^^

// Prettier 3.6.1
export const version: string;
```

##### Miscellaneous: Avoid closing files multiple times
([#&#8203;17665](https://redirect.github.com/prettier/prettier/pull/17665)
by [@&#8203;43081j](https://redirect.github.com/43081j))

When reading a file to infer the interpreter from a shebang, we use the
`n-readlines` library to read the first line in order to get the
shebang.

This library closes files when it reaches EOF, and we later try close
the same
files again. We now close files only if `n-readlines` did not already
close
them.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At 09:00 PM through 11:59 PM and 12:00
AM through 06:59 AM ( * 21-23,0-6 * * * ), Only on Sunday and Saturday (
* * * * 0,6 ) in timezone Europe/Berlin, Automerge - At 09:00 PM through
11:59 PM and 12:00 AM through 06:59 AM ( * 21-23,0-6 * * * ), Only on
Sunday and Saturday ( * * * * 0,6 ) in timezone Europe/Berlin.

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/gnosisguild/zodiac-pilot).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC42Mi4xIiwidXBkYXRlZEluVmVyIjoiNDAuNjIuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>